version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: job_queue_db
    environment:
      POSTGRES_USER: jobqueue
      POSTGRES_PASSWORD: jobqueue
      POSTGRES_DB: job_queue
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: